org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

group = fi.dy.masa
mod_id = litematica
mod_name = Litematica
author = masa
mod_file_name = litematica-fabric

#Fabric Properties - https://fabricmc.net/versions.html
# Current mod version
mod_version = 0.17.3

# Required malilib version
malilib_version = 0.18.2

# Minecraft, Fabric and mappings versions -- version out ties to malilib, requires that one to be released first.
minecraft_version_out = 1.20.6
minecraft_version = 1.20.6
mappings_version = 1.20.6+build.1

fabric_loader_version = 0.15.10
mod_menu_version = 9.0.0-pre.1
